baseURL = 'https://cookbook.mostlyharmless.cafe'
languageCode = 'en-us'
title = 'Mostly Harmless Cafe'
uglyURLs = true
publishDir = 'docs'
defaultMarkdownHandler = "goldmark"

[params]
	description = ""
	image = ""
	caption = ""
	alt = ""

[taxonomies]
	tag = 'tags'
	credit = 'credits'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
[goldmark]
	[Extensions]
		footnote = true

