#!/bin/zsh

if [ $1 ]
then
	for file in $@
	do
		convert -verbose -quality 60 $file -auto-orient ../${file%.*}.webp
	done
else
	for file in *.(jpg|png|jpeg)
	do
		convert -verbose -quality 60 $file -auto-orient ../${file%.(jpg|jpeg|png)}.webp
	done
fi
